# Generated by Django 5.0.7 on 2025-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_generalsupervisor_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homework',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
