# Generated by Django 5.0.7 on 2025-03-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homework_files_homework_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='files',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='images',
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homework')),
            ],
        ),
    ]
