# Generated by Django 5.0.7 on 2025-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homework_files_remove_homework_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcorrection',
            name='margin1',
        ),
        migrations.RemoveField(
            model_name='examcorrection',
            name='margin2',
        ),
        migrations.RemoveField(
            model_name='examcorrection',
            name='margin3',
        ),
        migrations.RemoveField(
            model_name='examcorrection',
            name='margin4',
        ),
        migrations.RemoveField(
            model_name='examcorrection',
            name='margin5',
        ),
    ]
