# Generated by Django 5.0.7 on 2025-03-21 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_examcorrection_margin1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
