# Generated by Django 5.0.7 on 2025-04-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_generalsupervisor_delete_teacher_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ManyToManyField(default=1, to='home.section'),
        ),
    ]
