# Generated by Django 5.0.7 on 2025-04-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_student_student_id_student_number_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('excused', 'مبرر'), ('unexcused', 'غير مبرر')], max_length=15)),
                ('dateTime', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان التقرير')),
                ('content', models.TextField(verbose_name='محتوى التقرير')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ التقرير')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='المادة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student', verbose_name='التلميذ')),
            ],
        ),
    ]
