# Generated by Django 5.0.7 on 2025-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_absence_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='absenceHours',
            field=models.IntegerField(default=0),
        ),
    ]
