# Generated by Django 5.0.7 on 2025-04-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_absence_absencehours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
