# Generated by Django 5.0.7 on 2025-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.TimeField(),
        ),
    ]
