# Generated by Django 5.0.7 on 2025-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_hour_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='hour',
            name='period',
            field=models.CharField(choices=[('Morning', 'الصباحية'), ('evening', 'المسائية')], default='none', max_length=20),
        ),
    ]
