# Generated by Django 5.0.7 on 2025-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_hour_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='period',
            field=models.CharField(choices=[('Morning', 'الصباحية'), ('evening', 'المسائية')], max_length=20),
        ),
    ]
