# Generated by Django 5.1.3 on 2025-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_hour_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='period',
            field=models.CharField(choices=[('الصباحية', 'الصباحية'), ('المسائية', 'المسائية')], max_length=20),
        ),
    ]
