# Generated by Django 5.0.7 on 2025-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_absence_absencehours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='dateTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('مبرر', 'مبرر'), ('غير مبرر', 'غير مبرر')], max_length=15),
        ),
    ]
