# Generated by Django 5.1.3 on 2025-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_absence_datetime_alter_absence_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-dateTime']},
        ),
        migrations.AddField(
            model_name='absence',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
