# Generated by Django 5.1.3 on 2025-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_absence_options_absence_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='counter',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
