# Generated by Django 5.1.8 on 2025-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_absence_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='counter',
            field=models.PositiveIntegerField(),
        ),
    ]
