# Generated by Django 5.1.8 on 2025-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_absence_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dateTime',
            field=models.DateField(null=True),
        ),
    ]
