# Generated by Django 5.0.7 on 2025-04-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_report_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dateTime',
        ),
    ]
