# Generated by Django 5.1.3 on 2025-04-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_report_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='instructions',
            field=models.TextField(default='/', verbose_name='الإجراء الواجب اتخاذه'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100, verbose_name='الإجراء الواجب اتخاذه'),
        ),
    ]
