# Generated by Django 5.0.7 on 2025-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_report_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='تاريخ التقرير'),
        ),
    ]
