# Generated by Django 5.1.8 on 2025-05-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
