# Generated by Django 5.1.3 on 2025-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_student_parentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
