# Generated by Django 5.1.8 on 2025-05-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='andctivities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.activities'),
        ),
        migrations.AddField(
            model_name='files',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AddField(
            model_name='image',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.activities'),
        ),
        migrations.AlterField(
            model_name='files',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homework'),
        ),
        migrations.AlterField(
            model_name='image',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
