# Generated by Django 5.1.8 on 2025-05-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_files_andctivities_files_course_image_activities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='andctivities',
            new_name='activities',
        ),
    ]
