# Generated by Django 5.1.8 on 2025-05-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_andctivities_files_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='activities',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.activities'),
        ),
        migrations.AlterField(
            model_name='files',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AlterField(
            model_name='files',
            name='homework',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homework'),
        ),
    ]
