# Generated by Django 5.1.8 on 2025-05-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_activities_files_activitie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='activities',
            new_name='activitie',
        ),
    ]
