# Generated by Django 5.0.7 on 2025-05-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_activities_image_activitie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='activitie',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='image',
            name='activitie',
        ),
        migrations.AddField(
            model_name='image',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.activities'),
        ),
        migrations.AlterField(
            model_name='image',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
