# Generated by Django 5.0.7 on 2025-05-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_activitie_files_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.activities'),
        ),
    ]
