# Generated by Django 5.0.7 on 2025-05-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='dateTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
