# Generated by Django 5.0.7 on 2025-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
