# Generated by Django 5.0.7 on 2025-05-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='files',
            name='course',
        ),
    ]
