# Generated by Django 5.0.7 on 2025-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_files_activity_remove_files_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PPR', models.IntegerField()),
                ('Mission', models.CharField(choices=[('أستاذ', 'أستاذ'), ('حارس عام', 'حارس عام'), ('ناظر', 'ناظر'), ('مدير', 'مدير'), ('مختص تربوي', 'مختص تربوي'), ('مختص اجتماعي', 'مختص اجتماعي'), ('مسير المصالح المادية والمالية', 'مسير المصالح المادية والمالية'), ('مختص الاقتصاد والإدارة', 'مختص الاقتصاد والإدارة')], max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
