# Generated by Django 5.0.7 on 2025-05-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_staff_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='UserName',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='User_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Mission',
            field=models.CharField(choices=[('أستاذ', 'أستاذ'), ('حارس عام', 'حارس عام'), ('مدير', 'مدير')], max_length=100),
        ),
    ]
