# Generated by Django 5.0.7 on 2025-05-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_userprofile_username_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='section',
        ),
    ]
