# Generated by Django 5.0.7 on 2025-05-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_userprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Mission',
            field=models.CharField(choices=[('أستاذ', 'أستاذ'), ('حارس عام', 'حارس عام'), ('مشرف', 'مشرف')], max_length=100),
        ),
    ]
