# Generated by Django 5.0.7 on 2025-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_staff_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='PPR',
            field=models.CharField(max_length=50),
        ),
    ]
