# Generated by Django 5.0.7 on 2025-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_staff_ppr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(default='ملف', max_length=100, null=True),
        ),
    ]
