# Generated by Django 5.1.8 on 2025-05-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_report_options_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section'),
        ),
    ]
