# Generated by Django 5.0.7 on 2025-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_absence_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
