# Generated by Django 5.0.7 on 2025-05-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_student_number_phone_alter_student_parentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='notes',
            field=models.CharField(default='بدون', max_length=200),
        ),
    ]
