# Generated by Django 5.0.7 on 2025-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_absence_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('MassarCode', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
