# Generated by Django 5.1.8 on 2025-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_number',
            name='Insurance_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='insurance_number',
            name='sport_ass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
