# Generated by Django 5.1.8 on 2025-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_insurance_number_insurance_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_number',
            name='Additional_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
