# Generated by Django 5.1.8 on 2025-06-24 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_insurance_number_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance_number',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
