# Generated by Django 5.1.8 on 2025-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_insurance_number_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_number',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
