# Generated by Django 5.0.7 on 2025-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_insurance_number_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammark',
            name='section',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='subject',
        ),
        migrations.AlterField(
            model_name='staff',
            name='Mission',
            field=models.CharField(choices=[('أستاذ', 'أستاذ'), ('حارس عام', 'حارس عام'), ('مشرف', 'مشرف'), ('مقتصد', 'مقتصد')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='ExamMark',
        ),
    ]
