# Generated by Django 5.2.4 on 2025-07-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_remove_exammark_section_remove_exammark_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='massar_num',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentEmail',
        ),
    ]
